name: Django CI 

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres_main:
        image: postgres:14.5 
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5   
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Coverage report
      env:
        DEBUG: "0"
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: "marceli"
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DB_HOST: "127.0.0.1"
        DB_DATABASE: "blog"
        DB_PORT: 5432
      run: |
        coverage run manage.py test
        coverage report
    - name: Django test
      env:
        DEBUG: "0"
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: "marceli"
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DB_HOST: "127.0.0.1"
        DB_DATABASE: "blog"
        DB_PORT: 5432
      run: |
        python3 manage.py test
